### ISSUE TITLE
How to change style of <Dot> component when using <DotGroup/> component?

### ISSUE THREAD

**Issue by VitaliiTsurkan** [express-labs/pure-react-carousel#137]
How to change style of <Dot> component when using <DotGroup/> component. 
I need to change border radius to make it round.
And I also want to change color of active <Dot>.

**Comment by tim-steele** [comment]
Hello @VitaliiTsurkan there are non-obfuscated classes made available for different pieces of the component that you can reference in your style sheet. Is that what you are looking for?

**Comment by VitaliiTsurkan** [comment]
Hello @tim-steele I'm not sure - I'm new to react, could you provide an example?

**Comment by mcb-job-tests** [comment]
override the default style...

`.carousel__dot--selected {
  background-color: <your fancy custom color > !important;
}`

**Comment by mrbinky3000** [comment]
You can also pass your own "className" prop to just about any component in Pure React Carousel and it will be appended to the list of classes for that component.

**Comment by UserSina** [comment]
Here, saving the time of whoever stumbles upon this in the future.

```JAVASCRIPT
<CarouselProvider 
...
>
  <DotGroup className="prc-dotGroup" />
<CarouselProvider />
```
```SCSS
.prc-dotGroup {
  text-align: center;
  padding-top: 5px;
  padding-bottom: 10px;
}
.carousel__dot {
  height: 15px;
  width: 15px;
  margin: 3px;
  border-radius: 50%;
  border: 1px solid black;
}
.carousel__dot--selected {
  background-color: black;
}
```
